feature/push-notifications-subscriptions
dialectlabs/data-service pull request #31
Opened 2022-07-29 15:56 UTC by kevindingens

- push notifications subscriptions support
  - new prisma tables
    - device - unique to a physicalId and push token (see README)
    - pushNotificationSubscription - many-to-many linker between wallets and devices
  - new device and pushNotification services
  - controller supporting the following endpoints
    - delete for a given physical deviceId
    - post, upserts a push token for a given device id
    - get, returns a token for a given device id (not needed but useful in unit testing and feels more robust)
    - all of the above associated to a wallet via JWT auth principal decorator

2022-07-29 16:58 UTC, tsmbl requested changes
Nicely done! Left several minor comments

2022-07-29 16:58 UTC, tsmbl commented on prisma/schema.prisma
> +  physicalId String @unique
let's follow snake case for all names i.e. here  @map("physical_id")

2022-07-29 16:58 UTC, tsmbl commented on prisma/schema.prisma
> +model Device {
Let's add createdAt, updatedAt attributes

2022-07-29 16:58 UTC, tsmbl commented on prisma/schema.prisma
> +model PushNotificationSubscription {
Let's add createdAt, updatedAt attributes

2022-07-29 16:58 UTC, tsmbl commented on src/push-notification/push-notification-subscriptions.controller.ts
> +  @Delete('/:physical_id')
Let's follow camelCase for parameters? Given we already use camelCase everywhere ;)

2022-07-29 16:58 UTC, tsmbl commented on src/push-notification/push-notification-subscriptions.controller.ts
> +    await this.pushNotificationService.delete(wallet.publicKey, physicalId);
I thinks we can pass wallet.id here instead of wallet.publicKey and avoid writing some code in service, wdyt? Same comment applies to other calls

2022-07-29 16:58 UTC, tsmbl commented on src/push-notification/push-notification-subscriptions.service.ts
> +    const fullWallet = await this.prisma.wallet.findUnique({
This select and console log is just for testing?

2022-07-29 16:58 UTC, tsmbl commented on prisma/schema.prisma
> +  device Device @relation(fields: [deviceId], references: [id])
I think we need to add cascades for relations, wdyt?
```
onDelete: Cascade, onUpdate: Cascade
```

2022-07-29 16:58 UTC, tsmbl commented on prisma/schema.prisma
> +  physicalId String @unique
Should be camel case here, I think `@map` is missing

2022-07-29 17:54 UTC, kevindingens commented on src/push-notification/push-notification-subscriptions.controller.ts
> +  @Delete('/:physical_id')
ah yes, went off of v0 which is inconsistent with this, 👍

2022-07-29 18:13 UTC, kevindingens commented on prisma/schema.prisma
> +  device Device @relation(fields: [deviceId], references: [id])
I omitted cascades since we don't currently have a use case for deleting a device and we don't necessarily need to delete a device when a subscription is deleted. Lets huddle about the update case if you think its convincing

2022-08-01 09:16 UTC, tsmbl approved these changes
Nice job, lgtm

2022-08-01 13:17 UTC, zhelezkov approved these changes

2022-08-01 15:25 UTC, merged