Feature/per channel broadcast
dialectlabs/data-service pull request #45
Opened 2022-08-19 18:31 UTC by Kiryous

2022-08-19 20:02 UTC, tsmbl approved these changes
Looks cool, also thanks for adding validator! Left some comments related to typing

2022-08-19 20:02 UTC, tsmbl commented on src/dapp-message/dapp-message.controller.dto.ts
> +const isTitleNeeded = (obj: any) =>
Why `any`?

2022-08-19 20:32 UTC, tsmbl requested changes
Let's fix typing comments and the gtg
Do you also plan to update sdk?

2022-08-20 15:56 UTC, tsmbl requested changes
Hey, thanks for addressing comments!

I've noticed a couple of compilation errors after your latest changes, could you please fix them?

2022-08-21 03:31 UTC, Kiryous commented
@tsmbl thanks for reviewing, esp on weekend! sorry, forgot to push something. Now ready!

2022-08-21 07:44 UTC, tsmbl approved these changes
Lgtm

2022-08-22 16:33 UTC, merged