feature: add website, heroUrl and index fields for Dapp
dialectlabs/data-service pull request #63
Opened 2022-09-19 13:36 UTC by Kiryous

TODO
- [ ] Add some tests

2022-09-19 15:22 UTC, tsmbl requested changes
Awesome! Added several comments

2022-09-20 09:10 UTC, Kiryous commented on prisma/schema.prisma
> +  heroUrl   String? @map("hero_url")
make sense, thx!

2022-09-20 09:10 UTC, Kiryous commented on src/dapp/dapp.controller.dto.ts
> +  @IsString()
there is, added

2022-09-20 09:10 UTC, Kiryous commented on prisma/schema.prisma
>    id          String  @id @default(uuid()) @db.Uuid
done!

2022-09-20 09:15 UTC, Kiryous commented on prisma/schema.prisma
>    id          String  @id @default(uuid()) @db.Uuid
added, nice catch!

2022-09-20 12:45 UTC, tsmbl requested changes
Overall lgtm, small comment, lmk wdyt

2022-09-20 12:45 UTC, tsmbl commented on src/dapp/dapp.controller.dto.ts
> +      ...(dapp.index && { index: dapp.index }),
let's omit this field in API, wdyt?

2022-09-20 13:05 UTC, Kiryous commented on src/dapp/dapp.controller.dto.ts
> +      ...(dapp.index && { index: dapp.index }),
agreed!

2022-09-22 08:03 UTC, tsmbl approved these changes

2022-09-22 08:04 UTC, merged