[CORE-220]: add bot blocked event + event handling
dialectlabs/data-service pull request #66
Opened 2022-09-23 16:14 UTC by Anglopol

2022-09-26 18:06 UTC, zhelezkov approved these changes
lgtm

2022-09-27 09:53 UTC, tsmbl requested changes
Overall good job, left a couple of comments

2022-09-27 09:53 UTC, tsmbl commented on src/dialect/dialect-events.ts
> +export enum TelegramEventType {
I think this event should be placed somewhere in telegram package, wdyt?

2022-09-27 09:53 UTC, tsmbl commented on src/telegram/telegram-bot.ts
>        this.logger.error(
I think we should rework logging, since we don't expect error logs when telegram bot is blocked by user

2022-09-27 11:39 UTC, tsmbl approved these changes
lgtm, nice job

2022-09-27 12:31 UTC, merged