Add limit to findAll function
dialectlabs/data-service pull request #67
Opened 2022-09-23 16:58 UTC by cholcombe973

This adds an optional limit parameter to the `findAll` function allowing callers to limit the results. Getting the last message now will be a `findall(query: "..", limit: 1)` function call.

2022-09-23 17:10 UTC, tsmbl requested changes
Hey, looks good, a couple of comments

1. Should we also update endpoint query?
2. If there's an endpoint query, let's prob move validation to dto via @Min decorator?
3. Let's append jira ticket name also in PR name in the next PRs, wdyt?

2022-09-26 18:40 UTC, tsmbl requested changes
Nice, added several comments/questions

2022-09-26 18:40 UTC, tsmbl commented on src/dialect/dialect.controller.dto.ts
> +  readonly value!: string;
Hey, should it be number and optional for backward compatibility sake?

e.g. example of how paging is done in FindDappMessagesQueryDto 
<img width="364" alt="image" src="https://user-images.githubusercontent.com/7888282/192354686-aeab61d8-ee34-4c8e-9491-52a7179c6a68.png">

2022-09-26 18:40 UTC, tsmbl commented on src/dialect/dialect.service.ts
> +    if (limit < 1) {
do we need this explicit validation if `@Min()` decorator is applied?

2022-09-26 18:40 UTC, tsmbl commented on src/dialect/dialect.controller.ts
> +    @Param('limit') limit: PositiveNumberDto,
I think this parameter should be included in query  `FindDialectQueryDto`, wdyt?

2022-09-26 20:07 UTC, cholcombe973 commented on src/dialect/dialect.controller.dto.ts
> +  readonly value!: string;
Neat! I like that.

2022-09-26 20:08 UTC, cholcombe973 commented on src/dialect/dialect.service.ts
> +    if (limit < 1) {
That's true. The validator should take care of it. I'll remove it.

2022-09-26 20:10 UTC, cholcombe973 commented on src/dialect/dialect.controller.ts
> +    @Param('limit') limit: PositiveNumberDto,
That sounds interesting. How would that work?

2022-09-27 10:05 UTC, tsmbl requested changes
Awesome, left a couple of comments / questions

2022-09-27 10:05 UTC, tsmbl commented on src/dialect/dialect.controller.dto.ts
> +  readonly take?: number;
I think it's ambiguous how this parameter is applied: to list of threads or to messages? Probably we can 1) extract pagination dto to be later used in other system modules 2) change dto to be explicit on what is paged. What do you think?

2022-09-27 10:05 UTC, tsmbl commented on src/dialect/dialect.controller.dto.ts
> +  readonly take?: number;
I think we should also use take parameter in other endpoints where the query is used, wdyt?

2022-09-27 16:11 UTC, cholcombe973 commented on src/dialect/dialect.controller.dto.ts
>  import { Type } from 'class-transformer';
Yeah Max/Min is used down at line 125/126

2022-09-27 18:36 UTC, cholcombe973 commented on src/dialect/dialect.controller.dto.ts
> +  readonly take?: number;
The consensus over slack DM's was that this is a bit of scope creep so we're going to push this change off to a future PR.

2022-09-27 19:05 UTC, tsmbl approved these changes
Awesome, lgtm!

2022-09-27 19:17 UTC, merged